# Generated by Django 6.0.4 on 2026-04-16 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='response',
        ),
        migrations.CreateModel(
            name='BoolAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bool', to='calendar_app.answer')),
            ],
        ),
        migrations.CreateModel(
            name='MultiAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multi', to='calendar_app.answer')),
                ('choices', models.ManyToManyField(to='calendar_app.choice')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='calendar_app.answer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAnswerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.choice')),
                ('order_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calendar_app.orderanswer')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('order_answer', 'position')},
            },
        ),
    ]
