# Generated by Django 6.0.4 on 2026-05-13 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_usermatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_questions', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceEthicalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ethical_profiles', to='calendar_app.choice')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.ethicalprofile')),
            ],
            options={
                'unique_together': {('choice', 'profile')},
            },
        ),
    ]
