# Generated by Django 6.0.4 on 2026-05-26 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0007_ethicalprofile_choiceethicalprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatchGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guessed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guessed_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_guesses', to=settings.AUTH_USER_MODEL)),
                ('user_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.usermatch')),
            ],
            options={
                'unique_together': {('user', 'user_match')},
            },
        ),
    ]
