# Generated by Django 6.0.4 on 2026-05-29 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0009_gift_giftguess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='image',
        ),
        migrations.RemoveField(
            model_name='usermatchguess',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='gift',
            name='difficulty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usermatchguess',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usermatchguess',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermatchguess',
            name='guessed_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_match_guesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermatchguess',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermatchguess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GiftGuess',
        ),
    ]
