# Generated by Django 6.0.4 on 2026-04-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_remove_answer_response_boolanswer_multianswer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MULTI', 'Multiple choice'), ('ORDER', 'Order preferences')], max_length=10),
        ),
        migrations.DeleteModel(
            name='BoolAnswer',
        ),
    ]
