# Generated by Django 6.0.4 on 2026-04-28 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_alter_question_question_type_delete_boolanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SingleChoiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.answer')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.choice')),
            ],
        ),
        migrations.DeleteModel(
            name='MultiAnswer',
        ),
    ]
