# Generated by Django 6.0.4 on 2026-05-03 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_answer_value_singlechoiceanswer_delete_multianswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='value',
        ),
    ]
